[package]
name = "tari_template_lib"
version = "0.35.1"
edition = "2021"

[dependencies]
tari_template_abi = { path = "../template_abi" }

borsh = "0.9.3"
serde = { version = "1.0.143", optional = true }
